[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.4.0"
lame = "0.1.3"
puremp3 = "0.1.0"
lame-sys = "0.1.2"
