[package]
name = "enc_monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "enc_monitor"
crate-type = ["cdylib"]

[dependencies]
vst = "0.2.1"
lame = { path = "../lame" }